import { CalculatorMeta, CalculatorCategory } from './types';

export const ALL_CALCULATORS: CalculatorMeta[] = [
  // --- Flooring & Tiling ---
  {
    id: 'tile',
    slug: 'tile-calculator',
    name: 'Tile Calculator',
    shortName: 'Tile',
    category: 'Flooring & Tiling',
    description: 'Calculate square footage, exact tile counts, waste buffers, and box quantities for straight, diagonal, or herringbone layouts.',
    metaTitle: 'Tile Calculator - Square Footage, Tile Count & Box Estimator',
    metaDescription: 'Free online tile calculator. Calculate how many tiles and boxes you need for floors and walls with waste allowance for straight or diagonal patterns.',
    keywords: ['tile calculator', 'how many tiles do i need', 'tile square footage', 'tile box calculator'],
    iconName: 'Grid',
  },
  {
    id: 'flooring',
    slug: 'flooring-calculator',
    name: 'Flooring Cost Calculator',
    shortName: 'Flooring',
    category: 'Flooring & Tiling',
    description: 'Estimate square footage, box requirements, waste factors, and total material costs for hardwood, laminate, vinyl plank, and tile.',
    metaTitle: 'Flooring Calculator - Square Footage, Boxes & Cost Estimator',
    metaDescription: 'Calculate hardwood, laminate, or vinyl plank flooring requirements, waste percentages, box counts, and estimated material costs.',
    keywords: ['flooring calculator', 'hardwood flooring cost', 'vinyl plank calculator', 'flooring square footage'],
    iconName: 'LayoutGrid',
  },
  {
    id: 'grout',
    slug: 'grout-calculator',
    name: 'Grout Calculator',
    shortName: 'Grout',
    category: 'Flooring & Tiling',
    description: 'Calculate pounds or kilograms of sanded, unsanded, or epoxy grout needed based on tile dimensions, joint width, and depth.',
    metaTitle: 'Grout Calculator - Pounds, Bags & Coverage Estimator',
    metaDescription: 'Free grout calculator. Calculate how many pounds or bags of grout you need for tile floors and backsplashes based on tile size and grout line width.',
    keywords: ['grout calculator', 'how much grout do i need', 'tile grout estimator', 'grout bag calculator'],
    iconName: 'Grid',
  },
  {
    id: 'subfloor',
    slug: 'subfloor-calculator',
    name: 'Subfloor & Underlayment Calculator',
    shortName: 'Subfloor',
    category: 'Flooring & Tiling',
    description: 'Estimate 4x8 plywood or OSB subfloor sheets, tongue-and-groove waste buffer, screws, and construction adhesive tubes.',
    metaTitle: 'Subfloor Calculator - 4x8 OSB & Plywood Sheet Estimator',
    metaDescription: 'Calculate how many 4x8 subfloor panels (1/2", 5/8", 3/4") you need for room floors, including fastener counts and subfloor glue tubes.',
    keywords: ['subfloor calculator', 'subfloor plywood sheets', 'osb subfloor estimator', 'underlayment calculator'],
    iconName: 'FileText',
  },
  {
    id: 'carpet',
    slug: 'carpet-calculator',
    name: 'Carpet & Padding Calculator',
    shortName: 'Carpet',
    category: 'Flooring & Tiling',
    description: 'Calculate square yards, square meters, roll lengths, tack strips, and padding for 12ft and 15ft carpet rolls.',
    metaTitle: 'Carpet Calculator - Square Yards, Roll Cut & Padding Estimator',
    metaDescription: 'Accurately calculate carpet square yards needed based on 12-foot roll widths, seam direction, waste factor, and carpet padding.',
    keywords: ['carpet calculator', 'square yards of carpet', 'how much carpet do i need', 'carpet padding calculator'],
    iconName: 'LayoutGrid',
  },
  {
    id: 'tile-mortar',
    slug: 'tile-mortar-calculator',
    name: 'Tile Mortar & Thinset Calculator',
    shortName: 'Thinset',
    category: 'Flooring & Tiling',
    description: 'Estimate 50lb bags of thinset mortar based on square footage and trowel notch size (1/4", 3/8", 1/2" or V-notch).',
    metaTitle: 'Tile Mortar Calculator - Thinset Bags & Trowel Sizing',
    metaDescription: 'Calculate how many 50lb bags of thinset mortar you need for floor and wall tile installations based on trowel notch size and substrate.',
    keywords: ['thinset calculator', 'tile mortar calculator', 'how much thinset for tile', 'trowel notch coverage'],
    iconName: 'Layers',
  },

  // --- Painting & Walls ---
  {
    id: 'paint',
    slug: 'paint-calculator',
    name: 'Paint Calculator',
    shortName: 'Paint',
    category: 'Painting & Walls',
    description: 'Estimate gallons or liters of paint needed based on room dimensions, door & window deductions, and coats.',
    metaTitle: 'Paint Calculator - Gallons, Liters & Coverage Estimator',
    metaDescription: 'Calculate how much paint you need in gallons or liters. Automatically subtract doors and windows to get the exact cans needed for walls and ceilings.',
    keywords: ['paint calculator', 'how much paint do i need', 'paint coverage calculator', 'wall paint estimator'],
    iconName: 'Paintbrush',
  },
  {
    id: 'primer',
    slug: 'primer-calculator',
    name: 'Primer Paint Calculator',
    shortName: 'Primer',
    category: 'Painting & Walls',
    description: 'Calculate primer gallons needed for bare drywall, stained wood, or masonry before painting.',
    metaTitle: 'Primer Calculator - Gallons for New Drywall & Bare Wood',
    metaDescription: 'Estimate primer gallons for walls and ceilings accounting for substrate porosity, drywall absorption, and door/window deductions.',
    keywords: ['primer calculator', 'how much primer do i need', 'drywall primer coverage', 'paint primer estimator'],
    iconName: 'Paintbrush',
  },
  {
    id: 'baseboard',
    slug: 'baseboard-calculator',
    name: 'Baseboard & Trim Calculator',
    shortName: 'Baseboard',
    category: 'Painting & Walls',
    description: 'Calculate linear feet, board quantities (8ft, 12ft, 16ft), finish nails, and caulk for perimeter baseboard trim.',
    metaTitle: 'Baseboard & Trim Calculator - Linear Feet & Board Counts',
    metaDescription: 'Free baseboard molding calculator. Deducts door openings and calculates 8ft, 12ft, or 16ft trim boards needed with miter waste allowance.',
    keywords: ['baseboard calculator', 'trim calculator', 'linear feet of baseboard', 'molding estimator'],
    iconName: 'Square',
  },
  {
    id: 'wallpaper',
    slug: 'wallpaper-calculator',
    name: 'Wallpaper Calculator',
    shortName: 'Wallpaper',
    category: 'Painting & Walls',
    description: 'Estimate wallpaper rolls needed based on wall dimensions, roll lengths, and pattern repeat drop allowances.',
    metaTitle: 'Wallpaper Calculator - Rolls Needed with Pattern Repeat',
    metaDescription: 'Free online wallpaper calculator. Determine how many rolls you need for any room, accounting for roll width, length, and pattern repeat waste.',
    keywords: ['wallpaper calculator', 'how many rolls of wallpaper do i need', 'wallpaper pattern repeat calculator'],
    iconName: 'Sparkles',
  },
  {
    id: 'drywall',
    slug: 'drywall-calculator',
    name: 'Drywall Sheet Calculator',
    shortName: 'Drywall',
    category: 'Painting & Walls',
    description: 'Calculate 4x8 or 4x12 drywall sheets, joint compound buckets, and drywall screws needed for walls and ceilings.',
    metaTitle: 'Drywall Calculator - Sheets, Joint Compound & Screws Estimator',
    metaDescription: 'Estimate drywall sheets (4x8 or 4x12), boxes of joint compound mud, and screw counts with door and window deductions.',
    keywords: ['drywall calculator', 'sheetrock calculator', 'how many sheets of drywall do i need', 'joint compound estimator'],
    iconName: 'Square',
  },
  {
    id: 'drywall-mud',
    slug: 'drywall-mud-calculator',
    name: 'Drywall Mud & Joint Compound Calculator',
    shortName: 'Drywall Mud',
    category: 'Painting & Walls',
    description: 'Calculate 4.5-gallon buckets of ready-mix joint compound, paper tape rolls, and corner bead for Level 3, 4, or 5 finishes.',
    metaTitle: 'Drywall Mud Calculator - Buckets of Joint Compound & Tape',
    metaDescription: 'Estimate joint compound buckets and paper tape rolls for taping, bed coating, and skim coating drywall seams.',
    keywords: ['drywall mud calculator', 'joint compound calculator', 'how much drywall mud do i need', 'drywall tape estimator'],
    iconName: 'Layers',
  },

  // --- Concrete & Masonry ---
  {
    id: 'concrete',
    slug: 'concrete-calculator',
    name: 'Concrete Volume & Bag Calculator',
    shortName: 'Concrete',
    category: 'Concrete & Masonry',
    description: 'Calculate concrete volume in cubic yards, cubic meters, ready-mix truckloads, and 40lb/60lb/80lb bags for slabs and footings.',
    metaTitle: 'Concrete Calculator - Cubic Yards, Meters & Bags Estimator',
    metaDescription: 'Accurately estimate concrete for slabs, patios, and footings. Calculates cubic yards, cubic meters, pre-mixed bags, and ready-mix truck loads.',
    keywords: ['concrete calculator', 'how much concrete do i need', 'concrete slab calculator', 'concrete bag estimator'],
    iconName: 'Layers',
  },
  {
    id: 'concrete-slab',
    slug: 'concrete-slab-calculator',
    name: 'Concrete Slab Cost & Volume Estimator',
    shortName: 'Concrete Slab',
    category: 'Concrete & Masonry',
    description: 'Comprehensive estimator for concrete slabs: ready-mix yards, sub-base gravel, rebar grid, edge forms, and material cost.',
    metaTitle: 'Concrete Slab Calculator - Cubic Yards, Gravel, Rebar & Cost',
    metaDescription: 'All-in-one concrete slab calculator. Estimate ready-mix yards, crushed gravel base, rebar reinforcement, and forming lumber.',
    keywords: ['concrete slab calculator', 'concrete patio cost', 'how many yards of concrete for a slab', 'driveway concrete estimator'],
    iconName: 'Layers',
  },
  {
    id: 'paver',
    slug: 'paver-calculator',
    name: 'Paver & Patio Base Calculator',
    shortName: 'Paver',
    category: 'Concrete & Masonry',
    description: 'Calculate patio paver counts (12x12, 6x9, 4x8), 1-inch bedding sand volume, crushed stone base, and edge restraints.',
    metaTitle: 'Paver Calculator - Patio Pavers, Sand Base & Gravel Estimator',
    metaDescription: 'Free paver calculator for patios, walkways, and driveways. Calculates pavers, bedding sand tons, and compacted gravel sub-base.',
    keywords: ['paver calculator', 'how many pavers do i need', 'patio paver estimator', 'paver sand base calculator'],
    iconName: 'Grid',
  },
  {
    id: 'retaining-wall',
    slug: 'retaining-wall-calculator',
    name: 'Retaining Wall Block Calculator',
    shortName: 'Retaining Wall',
    category: 'Concrete & Masonry',
    description: 'Calculate retaining wall blocks (4x12, 6x16, 8x18), buried base courses, cap blocks, and drainage gravel backfill.',
    metaTitle: 'Retaining Wall Calculator - Blocks, Courses & Gravel Estimator',
    metaDescription: 'Estimate retaining wall blocks, wall courses, cap stones, and drainage gravel needed for gravity and garden retaining walls.',
    keywords: ['retaining wall calculator', 'how many retaining wall blocks do i need', 'cinder block wall calculator'],
    iconName: 'Layers',
  },
  {
    id: 'brick',
    slug: 'brick-calculator',
    name: 'Brick & Mortar Wall Calculator',
    shortName: 'Brick',
    category: 'Concrete & Masonry',
    description: 'Calculate standard and modular brick quantities, pre-mixed mortar bags, and masonry sand for single or double wythe walls.',
    metaTitle: 'Brick Calculator - Bricks, Mortar Bags & Sand Estimator',
    metaDescription: 'Free brick calculator. Accurately calculate how many modular or standard bricks and mortar bags you need for brick walls and veneers.',
    keywords: ['brick calculator', 'how many bricks do i need', 'brick mortar calculator', 'masonry wall estimator'],
    iconName: 'Square',
  },
  {
    id: 'rebar',
    slug: 'rebar-calculator',
    name: 'Rebar & Mesh Reinforcement Calculator',
    shortName: 'Rebar',
    category: 'Concrete & Masonry',
    description: 'Calculate 20ft rebar sticks, grid intersections, tie wire pounds, and support chairs for concrete slab reinforcement.',
    metaTitle: 'Rebar Calculator - 20ft Sticks, Grid Spacing & Tie Wire',
    metaDescription: 'Estimate rebar sticks, grid layout (12" or 18" OC), lap splice allowance, and tie wire for concrete driveways, foundations, and footings.',
    keywords: ['rebar calculator', 'how much rebar do i need', 'concrete reinforcement calculator', 'rebar grid spacing'],
    iconName: 'Grid',
  },

  // --- Structures ---
  {
    id: 'wall-framing',
    slug: 'wall-framing-calculator',
    name: 'Wall Framing & Stud Calculator',
    shortName: 'Studs',
    category: 'Structures',
    description: 'Calculate 2x4 and 2x6 framing studs (16" or 24" OC), top and bottom plates, door/window headers, and framing nails.',
    metaTitle: 'Wall Framing Calculator - 2x4 Studs, Plates & Nail Estimator',
    metaDescription: 'Calculate how many 2x4 or 2x6 studs you need for wall framing with 16" or 24" on-center spacing, top/bottom plates, and corners.',
    keywords: ['wall framing calculator', 'stud calculator', 'how many studs do i need', '2x4 wall framing estimator'],
    iconName: 'Hammer',
  },
  {
    id: 'plywood',
    slug: 'plywood-calculator',
    name: 'Plywood & Sheet Goods Calculator',
    shortName: 'Plywood',
    category: 'Structures',
    description: 'Calculate 4x8, 4x9, 4x10, or 5x5 plywood, OSB, or MDF sheets needed for subfloors, walls, and roofs.',
    metaTitle: 'Plywood & Sheet Goods Calculator - 4x8, OSB & Subfloor Estimator',
    metaDescription: 'Determine how many sheets of plywood, OSB, or sheet goods you need with customizable waste allowances and sheet dimensions.',
    keywords: ['plywood calculator', '4x8 sheet calculator', 'osb calculator', 'subfloor sheet estimator'],
    iconName: 'FileText',
  },
  {
    id: 'deck',
    slug: 'deck-calculator',
    name: 'Deck Board Calculator',
    shortName: 'Decking',
    category: 'Structures',
    description: 'Estimate decking boards, total linear feet, spacing gaps, and hidden fastener screw counts for composite or wood decks.',
    metaTitle: 'Deck Board Calculator - Boards, Linear Feet & Screws Estimator',
    metaDescription: 'Calculate deck boards, total linear feet, waste factor, and fastener counts for standard 8ft, 10ft, 12ft, and 16ft lumber lengths.',
    keywords: ['deck board calculator', 'deck linear feet calculator', 'decking estimator', 'composite deck calculator'],
    iconName: 'Hammer',
  },
  {
    id: 'deck-railing',
    slug: 'deck-railing-calculator',
    name: 'Deck Railing & Baluster Calculator',
    shortName: 'Deck Railing',
    category: 'Structures',
    description: 'Calculate 4x4 posts, top/bottom 2x4 rails, vertical balusters, and exact spacing compliant with the 4-inch sphere building code.',
    metaTitle: 'Deck Railing Calculator - Posts, Rails & Baluster Spacing',
    metaDescription: 'Estimate deck guardrail materials: 4x4 posts, 2x4 rails, and code-compliant baluster spacing (IRC 4-inch sphere rule).',
    keywords: ['deck railing calculator', 'baluster spacing calculator', 'deck spindle estimator', 'guardrail calculator'],
    iconName: 'Hammer',
  },
  {
    id: 'deck-footing',
    slug: 'deck-footing-calculator',
    name: 'Deck Post & Footing Depth Calculator',
    shortName: 'Deck Footing',
    category: 'Structures',
    description: 'Calculate Sonotube diameter, frost line depth, concrete bags per hole, and post anchor brackets for deck piers.',
    metaTitle: 'Deck Footing Calculator - Sonotube, Frost Depth & Concrete Bags',
    metaDescription: 'Determine deck footing depths below local frost lines, Sonotube tube concrete volume, and 60lb/80lb bag requirements.',
    keywords: ['deck footing calculator', 'concrete pier calculator', 'sonotube concrete calculator', 'frost depth footing'],
    iconName: 'Layers',
  },
  {
    id: 'stair-stringer',
    slug: 'stair-stringer-calculator',
    name: 'Stair Stringer & Step Calculator',
    shortName: 'Stairs',
    category: 'Structures',
    description: 'Calculate step count, exact riser height, tread depth, total horizontal run, and 2x12 stringer board length.',
    metaTitle: 'Stair Stringer Calculator - Riser Height, Run & Steps Estimator',
    metaDescription: 'Free stair stringer calculator. Calculates exact riser height, tread run, stringer length, and incline angle with IRC building code checks.',
    keywords: ['stair stringer calculator', 'stair calculator', 'how to calculate stair stringers', 'riser and tread calculator'],
    iconName: 'Hammer',
  },
  {
    id: 'board-feet',
    slug: 'board-feet-calculator',
    name: 'Board Feet & Lumber Cost Calculator',
    shortName: 'Board Feet',
    category: 'Structures',
    description: 'Calculate board feet (BF = T × W × L / 12), cubic meters, and lumber costs for hardwood timber and carpentry projects.',
    metaTitle: 'Board Feet Calculator - Lumber Volume & Hardwood Cost Estimator',
    metaDescription: 'Free board feet calculator for woodworkers and carpenters. Calculate board footage from thickness, width, length, and quantity with lumber pricing.',
    keywords: ['board feet calculator', 'lumber calculator', 'how to calculate board feet', 'hardwood cost estimator'],
    iconName: 'Hammer',
  },

  // --- Mechanical & Roof ---
  {
    id: 'roofing',
    slug: 'roofing-calculator',
    name: 'Roofing Shingle Calculator',
    shortName: 'Roofing',
    category: 'Mechanical & Roof',
    description: 'Calculate roof squares, asphalt shingle bundles, and waste percentages adjusted for roof pitch multipliers.',
    metaTitle: 'Roofing Shingle Calculator - Roof Squares & Bundles Estimator',
    metaDescription: 'Accurately calculate roofing squares and shingle bundles for any roof pitch, with waste allowances for hips, valleys, and ridges.',
    keywords: ['roofing calculator', 'shingle bundle calculator', 'roof squares calculator', 'roof pitch multiplier'],
    iconName: 'Home',
  },
  {
    id: 'gutter',
    slug: 'gutter-calculator',
    name: 'Gutter Length & Downspout Calculator',
    shortName: 'Gutters',
    category: 'Mechanical & Roof',
    description: 'Calculate linear feet of 5" or 6" rain gutters, downspouts (1 per 35ft rule), end caps, corners, and fascia hangers.',
    metaTitle: 'Gutter Calculator - Linear Feet, Downspouts & Hangers',
    metaDescription: 'Calculate rain gutter linear footage, downspout counts, end caps, and mounting hangers based on roof perimeter and fascia run.',
    keywords: ['gutter calculator', 'how many downspouts do i need', 'rain gutter linear footage', 'gutter hanger calculator'],
    iconName: 'Home',
  },
  {
    id: 'siding',
    slug: 'siding-calculator',
    name: 'Siding & Squares Calculator',
    shortName: 'Siding',
    category: 'Mechanical & Roof',
    description: 'Calculate siding squares (100 sq ft), vinyl lap panels, starter strips, and J-channel molding with window deductions.',
    metaTitle: 'Siding Calculator - Siding Squares, Panels & Trim Estimator',
    metaDescription: 'Free siding calculator. Estimate squares of vinyl, fiber cement, or wood siding needed for exterior home walls with opening deductions.',
    keywords: ['siding calculator', 'how many squares of siding', 'vinyl siding calculator', 'lap siding estimator'],
    iconName: 'Home',
  },
  {
    id: 'shed-roof',
    slug: 'shed-roof-calculator',
    name: 'Shed Roof & Lean-To Calculator',
    shortName: 'Shed Roof',
    category: 'Mechanical & Roof',
    description: 'Calculate rafter lengths, roof pitch angle, 4x8 plywood sheathing sheets, and roofing squares for lean-to shed roofs.',
    metaTitle: 'Shed Roof Calculator - Lean-To Rafter Length & Pitch',
    metaDescription: 'Calculate rafter lumber length, overhangs, sheathing sheets, and slope angle for lean-to shed and patio roofs.',
    keywords: ['shed roof calculator', 'lean to calculator', 'shed rafter length', 'mono pitch roof calculator'],
    iconName: 'Home',
  },
  {
    id: 'insulation',
    slug: 'insulation-calculator',
    name: 'Insulation Batts & Rolls Calculator',
    shortName: 'Insulation',
    category: 'Mechanical & Roof',
    description: 'Calculate insulation rolls and batts needed for walls, attics, and crawlspaces across R-13, R-19, R-30, R-38, and R-49 ratings.',
    metaTitle: 'Insulation Calculator - Batts, Rolls & R-Value Estimator',
    metaDescription: 'Estimate rolls and batts of fiberglass or mineral wool insulation needed based on area and target R-value (R-13 to R-49).',
    keywords: ['insulation calculator', 'r value insulation estimator', 'how many rolls of insulation do i need', 'attic insulation calculator'],
    iconName: 'Shield',
  },
  {
    id: 'attic-ventilation',
    slug: 'attic-ventilation-calculator',
    name: 'Attic Ventilation & Ridge Vent Calculator',
    shortName: 'Attic Vent',
    category: 'Mechanical & Roof',
    description: 'Calculate Net Free Vent Area (NFVA) under the 1:300 code rule, continuous ridge vent footage, and soffit intake vents.',
    metaTitle: 'Attic Ventilation Calculator - Ridge & Soffit Vent Sizing',
    metaDescription: 'Calculate required attic ventilation based on IRC 1:300 code standard. Sizing for balanced intake soffit vents and ridge vent exhaust.',
    keywords: ['attic ventilation calculator', 'ridge vent calculator', 'soffit vent sizing', 'net free vent area calculator'],
    iconName: 'Home',
  },
  {
    id: 'hvac-btu',
    slug: 'hvac-btu-calculator',
    name: 'HVAC BTU & AC Tonnage Sizing Calculator',
    shortName: 'HVAC BTU',
    category: 'Mechanical & Roof',
    description: 'Estimate room heating and cooling BTU requirements and AC tonnage adjusted for ceiling height, climate zone, and insulation.',
    metaTitle: 'HVAC BTU Calculator - Room AC Sizing & Heating BTU Estimator',
    metaDescription: 'Calculate required BTU heating and air conditioning tonnage based on square footage, ceiling height, insulation quality, and climate.',
    keywords: ['hvac btu calculator', 'ac tonnage calculator', 'how many btu do i need', 'air conditioner room sizing'],
    iconName: 'Flame',
  },

  // --- Landscaping ---
  {
    id: 'mulch-soil',
    slug: 'mulch-soil-calculator',
    name: 'Mulch, Soil & Topsoil Calculator',
    shortName: 'Mulch & Soil',
    category: 'Landscaping',
    description: 'Calculate cubic yards, cubic meters, standard bags, and bulk truckloads for garden mulch, topsoil, compost, and gravel.',
    metaTitle: 'Mulch, Soil & Gravel Calculator - Cubic Yards & Bags Estimator',
    metaDescription: 'Estimate cubic yards and bags of mulch, topsoil, and gravel for landscaping beds, garden projects, and pathways.',
    keywords: ['mulch calculator', 'soil calculator', 'cubic yards of dirt', 'how much mulch do i need', 'gravel calculator'],
    iconName: 'Trees',
  },
  {
    id: 'gravel',
    slug: 'gravel-calculator',
    name: 'Driveway & Pathway Gravel Calculator',
    shortName: 'Gravel',
    category: 'Landscaping',
    description: 'Calculate tons, cubic yards, and 50lb bags of crushed stone or pea gravel for driveways, French drains, and garden paths.',
    metaTitle: 'Gravel Calculator - Tons & Cubic Yards for Driveways & Paths',
    metaDescription: 'Calculate how many tons or cubic yards of gravel, crushed stone, or pea rock you need for driveways and landscape pathways.',
    keywords: ['gravel calculator', 'how much gravel do i need', 'driveway gravel calculator', 'tons of crushed stone'],
    iconName: 'Layers',
  },
  {
    id: 'sod',
    slug: 'sod-calculator',
    name: 'Sod & Lawn Turf Calculator',
    shortName: 'Sod',
    category: 'Landscaping',
    description: 'Calculate lawn turf rolls (standard 2ft x 5ft), pallets, topsoil dressing prep, and waste buffers for new sod installation.',
    metaTitle: 'Sod Calculator - Rolls, Pallets & Square Feet Estimator',
    metaDescription: 'Calculate how many rolls and pallets of sod you need to turf your lawn, with waste percentage and topsoil bed preparation.',
    keywords: ['sod calculator', 'how many pallets of sod do i need', 'lawn turf calculator', 'grass roll estimator'],
    iconName: 'Trees',
  },
  {
    id: 'fence',
    slug: 'fence-calculator',
    name: 'Fence Material Calculator',
    shortName: 'Fence',
    category: 'Landscaping',
    description: 'Estimate fence posts, privacy panels, pickets, horizontal rails, and gate openings for wood or vinyl perimeter fencing.',
    metaTitle: 'Fence Calculator - Posts, Rails, Panels & Pickets Estimator',
    metaDescription: 'Calculate materials for privacy, picket, or post-and-rail fences: posts, rails, pickets, panels, and gate clearances.',
    keywords: ['fence calculator', 'how many fence pickets do i need', 'fence post calculator', 'fence material estimator'],
    iconName: 'Trees',
  },
  {
    id: 'french-drain',
    slug: 'french-drain-calculator',
    name: 'French Drain & Drainage Trench Calculator',
    shortName: 'French Drain',
    category: 'Landscaping',
    description: 'Calculate trench excavation cubic yards, 3/4" drainage gravel tons, 4" perforated pipe footage, and geotextile filter fabric.',
    metaTitle: 'French Drain Calculator - Gravel Tons, Pipe & Fabric Estimator',
    metaDescription: 'Calculate materials needed for a French drain: drainage gravel tons, perforated pipe length, and geotextile filter fabric wrap.',
    keywords: ['french drain calculator', 'drainage gravel calculator', 'perforated pipe length', 'trench gravel calculator'],
    iconName: 'Layers',
  },
  {
    id: 'driveway-sealer',
    slug: 'driveway-sealer-calculator',
    name: 'Asphalt Driveway Sealer Calculator',
    shortName: 'Driveway Sealer',
    category: 'Landscaping',
    description: 'Estimate 5-gallon pails of asphalt emulsion driveway sealer, total gallons, and rubberized crack filler based on surface condition.',
    metaTitle: 'Driveway Sealer Calculator - 5-Gallon Pails & Crack Filler',
    metaDescription: 'Calculate how many 5-gallon pails of asphalt driveway sealer you need based on driveway dimensions and pavement porosity.',
    keywords: ['driveway sealer calculator', 'how much driveway sealer do i need', 'asphalt sealer pails', 'blacktop sealer estimator'],
    iconName: 'Layers',
  },

  // --- Electrical & Trades ---
  {
    id: 'wire-gauge',
    slug: 'wire-gauge-calculator',
    name: 'Electrical Wire Gauge & Voltage Drop Calculator',
    shortName: 'Wire Gauge',
    category: 'Electrical & Trades',
    description: 'Calculate recommended AWG wire gauge (14, 12, 10, 8, 6, 4) and verify voltage drop is under the 3% NEC limit for 120V/240V circuits.',
    metaTitle: 'Wire Gauge Calculator - Voltage Drop & AWG Sizing (NEC)',
    metaDescription: 'Determine the correct electrical wire gauge and calculate voltage drop across distance for 120V and 240V circuits under NEC standards.',
    keywords: ['wire gauge calculator', 'voltage drop calculator', 'nec wire size calculator', 'electrical wire ampacity'],
    iconName: 'Lightbulb',
  },
  {
    id: 'plumbing-pipe',
    slug: 'plumbing-pipe-calculator',
    name: 'Plumbing Supply Pipe Sizing Calculator',
    shortName: 'Plumbing Pipe',
    category: 'Electrical & Trades',
    description: 'Size main water supply and branch lines (Copper/PEX) based on Water Supply Fixture Units (WSFU) and peak flow rate GPM.',
    metaTitle: 'Plumbing Pipe Sizing Calculator - WSFU & GPM Flow Estimator',
    metaDescription: 'Calculate water supply pipe sizes for residential plumbing based on fixture unit counts (WSFU) and developed pipe length.',
    keywords: ['plumbing pipe sizing calculator', 'water pipe size', 'wsfu calculator', 'pex pipe sizing'],
    iconName: 'Wrench',
  },
  {
    id: 'cabinet-hardware',
    slug: 'cabinet-hardware-calculator',
    name: 'Cabinet Hardware & Drawer Pull Spacing Calculator',
    shortName: 'Cabinet Hardware',
    category: 'Electrical & Trades',
    description: 'Calculate drill hole positions from edges, center-to-center pull spacing, and single vs dual pull layouts on kitchen cabinets.',
    metaTitle: 'Cabinet Hardware Calculator - Drawer Pull Hole Spacing',
    metaDescription: 'Accurately find drill hole locations for cabinet knobs and drawer pulls using the Rule of Thirds or centered hardware guidelines.',
    keywords: ['cabinet hardware calculator', 'drawer pull spacing', 'cabinet pull placement', 'drill hole spacing for drawer pulls'],
    iconName: 'Wrench',
  },
  {
    id: 'epoxy-floor',
    slug: 'epoxy-floor-calculator',
    name: 'Epoxy Garage Floor Coating Calculator',
    shortName: 'Epoxy Floor',
    category: 'Electrical & Trades',
    description: 'Calculate epoxy coating gallons, decorative color flakes, anti-slip additive, and acid etch cleaner for 1-car, 2-car, or 3-car garages.',
    metaTitle: 'Epoxy Floor Calculator - Garage Coating Kits & Flake Estimator',
    metaDescription: 'Estimate epoxy gallons, DIY garage floor coating kits, color flakes, and clear topcoat for 1-car, 2-car, and 3-car garage floors.',
    keywords: ['epoxy floor calculator', 'garage floor coating estimator', 'how much epoxy for garage floor', 'epoxy flake coverage'],
    iconName: 'Paintbrush',
  },
];

export const CATEGORIES: CalculatorCategory[] = [
  'Flooring & Tiling',
  'Painting & Walls',
  'Concrete & Masonry',
  'Structures',
  'Mechanical & Roof',
  'Landscaping',
  'Electrical & Trades',
];

export function getCalculatorBySlug(slug: string): CalculatorMeta | undefined {
  return ALL_CALCULATORS.find((c) => c.slug === slug);
}

export function getRelatedCalculators(currentSlug: string, count: number = 6): CalculatorMeta[] {
  const current = getCalculatorBySlug(currentSlug);
  if (!current) return ALL_CALCULATORS.slice(0, count);

  // Prioritize calculators in the same category, then others
  const sameCategory = ALL_CALCULATORS.filter(
    (c) => c.slug !== currentSlug && c.category === current.category
  );
  const otherCategories = ALL_CALCULATORS.filter(
    (c) => c.slug !== currentSlug && c.category !== current.category
  );

  return [...sameCategory, ...otherCategories].slice(0, count);
}
